"""agent/report/html_report.py – Jinja2-powered HTML report."""
from __future__ import annotations

from jinja2 import Environment, BaseLoader

_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>API Test Report — {{ report.service }}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; margin: 0; background: #f5f7fa; color: #1a202c; }
    header { background: #2563eb; color: white; padding: 1.5rem 2rem; }
    header h1 { margin: 0; font-size: 1.5rem; }
    header p  { margin: .25rem 0 0; opacity: .85; font-size: .9rem; }
    main { max-width: 1100px; margin: 2rem auto; padding: 0 1rem; }

    .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
    .card  { background: white; border-radius: 8px; padding: 1.2rem; text-align: center; box-shadow: 0 1px 3px rgba(0,0,0,.1); }
    .card .val  { font-size: 2rem; font-weight: 700; }
    .card .label{ font-size: .8rem; color: #6b7280; margin-top: .25rem; }
    .pass { color: #059669; }
    .fail { color: #dc2626; }
    .info { color: #2563eb; }

    table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,.1); }
    th { background: #1e3a8a; color: white; text-align: left; padding: .75rem 1rem; font-size: .8rem; text-transform: uppercase; letter-spacing: .05em; }
    td { padding: .7rem 1rem; font-size: .85rem; border-bottom: 1px solid #e5e7eb; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #f0f4ff; }
    .badge { display: inline-block; padding: .2rem .55rem; border-radius: 9999px; font-size: .75rem; font-weight: 600; }
    .badge-pass { background: #d1fae5; color: #065f46; }
    .badge-fail { background: #fee2e2; color: #991b1b; }
    .badge-pos  { background: #dbeafe; color: #1e40af; }
    .badge-neg  { background: #fef3c7; color: #92400e; }
    .badge-sch  { background: #ede9fe; color: #5b21b6; }

    footer { text-align: center; padding: 2rem; color: #9ca3af; font-size: .8rem; }
  </style>
</head>
<body>
<header>
  <h1>API Test Report — {{ report.service | upper }}</h1>
  <p>{{ report.total_apis }} APIs &nbsp;·&nbsp; {{ report.total_tests }} tests &nbsp;·&nbsp; Pass rate {{ report.pass_rate_pct }}%</p>
</header>
<main>
  <div class="cards">
    <div class="card"><div class="val info">{{ report.total_apis }}</div><div class="label">APIs Tested</div></div>
    <div class="card"><div class="val info">{{ report.total_tests }}</div><div class="label">Total Tests</div></div>
    <div class="card"><div class="val pass">{{ report.passed }}</div><div class="label">Passed</div></div>
    <div class="card"><div class="val fail">{{ report.failed }}</div><div class="label">Failed</div></div>
    <div class="card"><div class="val info">{{ report.pass_rate_pct }}%</div><div class="label">Pass Rate</div></div>
    <div class="card"><div class="val info">{{ report.avg_latency_ms }}</div><div class="label">Avg Latency (ms)</div></div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Test ID</th>
        <th>API</th>
        <th>Type</th>
        <th>Description</th>
        <th>Expected</th>
        <th>Actual</th>
        <th>Latency (ms)</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      {% for r in report.details %}
      <tr>
        <td>{{ loop.index }}</td>
        <td><code>{{ r.test_id }}</code></td>
        <td><code>{{ r.api_id }}</code></td>
        <td>
          <span class="badge badge-{% if r.test_type=='positive' %}pos{% elif r.test_type=='negative' %}neg{% else %}sch{% endif %}">
            {{ r.test_type }}
          </span>
        </td>
        <td>{{ r.description }}</td>
        <td>{{ r.expected_status }}</td>
        <td>{{ r.actual_status if r.actual_status is not none else '—' }}</td>
        <td>{{ r.latency_ms }}</td>
        <td><span class="badge badge-{% if r.status=='passed' %}pass{% else %}fail{% endif %}">{{ r.status }}</span></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>
<footer>Generated by Spec-Driven API Testing Agent</footer>
</body>
</html>
"""


def build(report: dict) -> str:
    env = Environment(loader=BaseLoader())
    tmpl = env.from_string(_TEMPLATE)
    return tmpl.render(report=report)
