"""agent/report/markdown_report.py – Markdown summary report."""
from __future__ import annotations


def build(report: dict) -> str:
    lines = [
        f"# API Test Report — {report['service'].upper()}",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| APIs Tested | {report['total_apis']} |",
        f"| Total Tests | {report['total_tests']} |",
        f"| Passed | ✅ {report['passed']} |",
        f"| Failed | ❌ {report['failed']} |",
        f"| Pass Rate | {report['pass_rate_pct']}% |",
        f"| Avg Latency | {report['avg_latency_ms']} ms |",
        "",
        "## Results by Type",
        "",
        "| Type | Total | Passed | Failed |",
        "|------|-------|--------|--------|",
    ]

    for t, m in report.get("metrics_by_type", {}).items():
        lines.append(f"| {t} | {m['total']} | {m['passed']} | {m['failed']} |")

    lines += [
        "",
        "## Detailed Results",
        "",
        "| Test ID | API | Type | Description | Expected | Actual | Latency (ms) | Status |",
        "|---------|-----|------|-------------|----------|--------|--------------|--------|",
    ]

    for r in report.get("details", []):
        status_icon = "✅" if r.get("status") == "passed" else "❌"
        actual = str(r.get("actual_status", "—"))
        lines.append(
            f"| `{r.get('test_id','')}` "
            f"| `{r.get('api_id','')}` "
            f"| {r.get('test_type','')} "
            f"| {r.get('description','')[:60]} "
            f"| {r.get('expected_status','')} "
            f"| {actual} "
            f"| {r.get('latency_ms', 0)} "
            f"| {status_icon} {r.get('status','')} |"
        )

    lines += ["", "---", "_Generated by Spec-Driven API Testing Agent_"]
    return "\n".join(lines)
